apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: kafka
      protocol: TCP
      name: kafka
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-headless
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: kafka
      protocol: TCP
      name: kafka
    - port: {{ .Values.service.controllerPort }}
      targetPort: controller
      protocol: TCP
      name: controller
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
