apiVersion: v2

name: ksqldb
version: 0.4.1

appVersion: 0.29.0

description: Confluent ksqlDB Helm Chart
type: application
icon: https://github.com/licenseware/helm-charts/raw/main/static/png/ksqldb.jpg

keywords:
  - ksqldb
  - confluent
  - ksql
  - kafka
  - streaming

dependencies:
  - condition: kafka.create
    name: kafka
    repository: https://charts.bitnami.com/bitnami/
    version: 30.1.x
