apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-connect-base.fullname" . }}
  labels:
    {{- include "kafka-connect-base.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: connect
      protocol: TCP
      name: http
  selector:
    {{- include "kafka-connect-base.selectorLabels" . | nindent 4 }}
